#!/usr/bin/env bash
. ./env.sh
cat cfg/nginx.conf | sed "s/PGDATABASE/$PGDATABASE/g"  | sed "s/PGPORT/$PGPORT/g" | sed "s/PGUSER/$PGUSER/g" | sed "s/PGPASSWORD/$PGPASSWORD/g" | sed "s|WEBROOT|$FHIR_ROOT/fnd|g" | sed "s/NGXPORT/$NGXPORT/g" > bin/nginx/conf/nginx.conf

bin/nginx/sbin/nginx -s stop || echo 'not running'
echo 'Starting nginx...'
bin/nginx/sbin/nginx
echo 'netstat'
netstat -pant | grep 5555
