#!/usr/bin/env bash
function recreate_db {
  echo 'Recreate database...'
  psql template1 -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$PGDATABASE' AND pid <> pg_backend_pid()"
  psql template1 -c "DROP DATABASE $PGDATABASE"
  psql template1 -c "CREATE DATABASE $PGDATABASE"
  curl https://raw.github.com/fhirbase/fhirbase/master/fhirbase.sql | psql $PGDATABASE
}

function update_code {
  echo 'Update code'
  git reset --hard
  git pull
  echo 'Compile code'
  . ./compile
  echo 'Restart nginx'
  . ./configure_nginx
}

. ./env.sh

CMD=$1

case "$CMD" in
    "recreate-db" )
      recreate_db
      ;;

    "update-code" )
      update_code
      ;;

    "full" )
      recreate_db
      update_code
      ;;
esac
