#!/usr/bin/env bash

if [ ! -f ./cfg/env.sh ]
then
  echo "Please cp cfg/env.sh.template cfg/env.sh # and set configuration"
  exit 1
fi

. ./cfg/env.sh
. ./sbin/recreate_db.sh
. ./sbin/ngx.sh
. ./sbin/frontend.sh

CMD=$1
case "$CMD" in
    "install_ngnx" )
      install_ngnx
      ;;
    "reload_ngx" )
      reload_ngx
      ;;
    "recreate_db" )
      recreate_db
      ;;
    "install_front" )
      install_front
      ;;
    "app" )
      reload_application_scripts
      ;;
    "fnd" )
      cd fnd && `npm bin`/grunt build watch
      ;;
    "all" )
      recreate_db
      reload_ngx
      ;;
    "deploy" )
      git pull
      #recreate_db
      install_front
      ;;
    *)
      cat <<EOF
subcommands:
* install_ngnx
* reload_ngx
* app - reload app sql scripts
* recreate_db
* all - drop db, load fhir db, reloadd pp scripts, reload ngx
* fnd - grunt watch & build
EOF
      exit
esac
